import { Router } from "express";
import authRouter from "./auth.routes";
import noteRouter from "./note.routes";
import { verifyUser } from "../middlewares";
import userRouter from "./user.routes";
const router = Router();
router.use("/auth", authRouter);
router.use("/notes", verifyUser, noteRouter);
router.use("/user", verifyUser, userRouter);
export default router;
