import { Router } from "express";
import authRouter from "./auth.routes";
import noteRouter from "./note.routes";
import { verifyUser } from "../middlewares";
import userRouter from "./user.routes";
import multer from "multer";
import imageRoutes from "./image.routes";
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });
const router = Router();
router.use("/auth", authRouter);
router.use("/notes", verifyUser, noteRouter);
router.use("/user", verifyUser, userRouter);
router.use("/images", verifyUser, upload.single("avater"), imageRoutes);
export default router;
